// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vessel/vessel.proto

package shippy_service_vessel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Vessel struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Capacity             int32    `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,3,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Available            bool     `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	OwerId               string   `protobuf:"bytes,6,opt,name=ower_id,json=owerId,proto3" json:"ower_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vessel) Reset()         { *m = Vessel{} }
func (m *Vessel) String() string { return proto.CompactTextString(m) }
func (*Vessel) ProtoMessage()    {}
func (*Vessel) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bd0828b40ed5ef5, []int{0}
}

func (m *Vessel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vessel.Unmarshal(m, b)
}
func (m *Vessel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vessel.Marshal(b, m, deterministic)
}
func (m *Vessel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vessel.Merge(m, src)
}
func (m *Vessel) XXX_Size() int {
	return xxx_messageInfo_Vessel.Size(m)
}
func (m *Vessel) XXX_DiscardUnknown() {
	xxx_messageInfo_Vessel.DiscardUnknown(m)
}

var xxx_messageInfo_Vessel proto.InternalMessageInfo

func (m *Vessel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Vessel) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Vessel) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

func (m *Vessel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vessel) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func (m *Vessel) GetOwerId() string {
	if m != nil {
		return m.OwerId
	}
	return ""
}

type Specification struct {
	Weight               int32    `protobuf:"varint,1,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Specification) Reset()         { *m = Specification{} }
func (m *Specification) String() string { return proto.CompactTextString(m) }
func (*Specification) ProtoMessage()    {}
func (*Specification) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bd0828b40ed5ef5, []int{1}
}

func (m *Specification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Specification.Unmarshal(m, b)
}
func (m *Specification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Specification.Marshal(b, m, deterministic)
}
func (m *Specification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Specification.Merge(m, src)
}
func (m *Specification) XXX_Size() int {
	return xxx_messageInfo_Specification.Size(m)
}
func (m *Specification) XXX_DiscardUnknown() {
	xxx_messageInfo_Specification.DiscardUnknown(m)
}

var xxx_messageInfo_Specification proto.InternalMessageInfo

func (m *Specification) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type CreateResp struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResp) Reset()         { *m = CreateResp{} }
func (m *CreateResp) String() string { return proto.CompactTextString(m) }
func (*CreateResp) ProtoMessage()    {}
func (*CreateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bd0828b40ed5ef5, []int{2}
}

func (m *CreateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResp.Unmarshal(m, b)
}
func (m *CreateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResp.Marshal(b, m, deterministic)
}
func (m *CreateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResp.Merge(m, src)
}
func (m *CreateResp) XXX_Size() int {
	return xxx_messageInfo_CreateResp.Size(m)
}
func (m *CreateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResp proto.InternalMessageInfo

func (m *CreateResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type FindAvailableResp struct {
	Vessels              []*Vessel `protobuf:"bytes,1,rep,name=vessels,proto3" json:"vessels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FindAvailableResp) Reset()         { *m = FindAvailableResp{} }
func (m *FindAvailableResp) String() string { return proto.CompactTextString(m) }
func (*FindAvailableResp) ProtoMessage()    {}
func (*FindAvailableResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bd0828b40ed5ef5, []int{3}
}

func (m *FindAvailableResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAvailableResp.Unmarshal(m, b)
}
func (m *FindAvailableResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAvailableResp.Marshal(b, m, deterministic)
}
func (m *FindAvailableResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAvailableResp.Merge(m, src)
}
func (m *FindAvailableResp) XXX_Size() int {
	return xxx_messageInfo_FindAvailableResp.Size(m)
}
func (m *FindAvailableResp) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAvailableResp.DiscardUnknown(m)
}

var xxx_messageInfo_FindAvailableResp proto.InternalMessageInfo

func (m *FindAvailableResp) GetVessels() []*Vessel {
	if m != nil {
		return m.Vessels
	}
	return nil
}

func init() {
	proto.RegisterType((*Vessel)(nil), "shippy.service.vessel.Vessel")
	proto.RegisterType((*Specification)(nil), "shippy.service.vessel.Specification")
	proto.RegisterType((*CreateResp)(nil), "shippy.service.vessel.CreateResp")
	proto.RegisterType((*FindAvailableResp)(nil), "shippy.service.vessel.FindAvailableResp")
}

func init() { proto.RegisterFile("vessel/vessel.proto", fileDescriptor_2bd0828b40ed5ef5) }

var fileDescriptor_2bd0828b40ed5ef5 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xdd, 0x4a, 0x33, 0x41,
	0x0c, 0xed, 0xf4, 0x67, 0xdb, 0xe6, 0xa3, 0x1f, 0x18, 0x51, 0x87, 0x62, 0xa1, 0x2e, 0xa2, 0x7b,
	0xb5, 0x42, 0xbd, 0xf0, 0x5a, 0x04, 0x41, 0xe8, 0xd5, 0x16, 0xf4, 0xb2, 0x4c, 0x67, 0xa3, 0x0d,
	0xb4, 0xdd, 0x61, 0x67, 0xed, 0xcf, 0xcb, 0xf8, 0x2c, 0x3e, 0x9a, 0x74, 0xa6, 0xb5, 0x14, 0xad,
	0x57, 0x93, 0x93, 0x9c, 0xe4, 0x24, 0x87, 0x81, 0xe3, 0x39, 0x59, 0x4b, 0x93, 0x1b, 0xff, 0xc4,
	0x26, 0xcf, 0x8a, 0x0c, 0x4f, 0xec, 0x98, 0x8d, 0x59, 0xc5, 0x96, 0xf2, 0x39, 0x6b, 0x8a, 0x7d,
	0x31, 0xfc, 0x10, 0x10, 0x3c, 0xbb, 0x10, 0xff, 0x43, 0x99, 0x53, 0x29, 0xba, 0x22, 0x6a, 0x26,
	0x65, 0x4e, 0xb1, 0x0d, 0x0d, 0xad, 0x8c, 0xd2, 0x5c, 0xac, 0x64, 0xb9, 0x2b, 0xa2, 0x5a, 0xf2,
	0x8d, 0xb1, 0x03, 0x30, 0x55, 0xcb, 0xe1, 0x82, 0xf8, 0x6d, 0x5c, 0xc8, 0x8a, 0xab, 0x36, 0xa7,
	0x6a, 0xf9, 0xe2, 0x12, 0x88, 0x50, 0x9d, 0xa9, 0x29, 0xc9, 0xaa, 0x1b, 0xe6, 0x62, 0x3c, 0x87,
	0xa6, 0x9a, 0x2b, 0x9e, 0xa8, 0xd1, 0x84, 0x64, 0xad, 0x2b, 0xa2, 0x46, 0xb2, 0x4b, 0xe0, 0x19,
	0xd4, 0xb3, 0x05, 0xe5, 0x43, 0x4e, 0x65, 0xe0, 0x9a, 0x82, 0x35, 0x7c, 0x4a, 0xc3, 0x6b, 0x68,
	0x0d, 0x0c, 0x69, 0x7e, 0x65, 0xad, 0x0a, 0xce, 0x66, 0x78, 0x0a, 0xc1, 0x46, 0x56, 0x38, 0xd9,
	0x0d, 0x0a, 0xaf, 0x00, 0x1e, 0x72, 0x52, 0x05, 0x25, 0x64, 0x0d, 0x4a, 0xa8, 0xdb, 0x77, 0xad,
	0xc9, 0x5a, 0x47, 0x6b, 0x24, 0x5b, 0x18, 0xf6, 0xe1, 0xe8, 0x91, 0x67, 0xe9, 0xfd, 0x56, 0xda,
	0xd1, 0xef, 0xa0, 0xee, 0x0d, 0x59, 0xd3, 0x2b, 0xd1, 0xbf, 0x5e, 0x27, 0xfe, 0xd5, 0xaf, 0xd8,
	0x7b, 0x95, 0x6c, 0xd9, 0xbd, 0x4f, 0x01, 0x2d, 0x9f, 0x1b, 0x78, 0x22, 0xf6, 0x21, 0xf0, 0x7b,
	0xe0, 0xdf, 0x33, 0xda, 0x17, 0x07, 0xca, 0xbb, 0x2b, 0xc2, 0x12, 0x2a, 0x68, 0xed, 0x6d, 0x8b,
	0x97, 0x07, 0xba, 0xf6, 0x4c, 0x6a, 0x47, 0x07, 0x58, 0x3f, 0x2e, 0x0f, 0x4b, 0xa3, 0xc0, 0x7d,
	0x90, 0xdb, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x6c, 0xce, 0x21, 0x37, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for VesselService service

type VesselServiceClient interface {
	Create(ctx context.Context, in *Vessel, opts ...client.CallOption) (*CreateResp, error)
	FindAvailable(ctx context.Context, in *Specification, opts ...client.CallOption) (*FindAvailableResp, error)
}

type vesselServiceClient struct {
	c           client.Client
	serviceName string
}

func NewVesselServiceClient(serviceName string, c client.Client) VesselServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "shippy.service.vessel"
	}
	return &vesselServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *vesselServiceClient) Create(ctx context.Context, in *Vessel, opts ...client.CallOption) (*CreateResp, error) {
	req := c.c.NewRequest(c.serviceName, "VesselService.Create", in)
	out := new(CreateResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vesselServiceClient) FindAvailable(ctx context.Context, in *Specification, opts ...client.CallOption) (*FindAvailableResp, error) {
	req := c.c.NewRequest(c.serviceName, "VesselService.FindAvailable", in)
	out := new(FindAvailableResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VesselService service

type VesselServiceHandler interface {
	Create(context.Context, *Vessel, *CreateResp) error
	FindAvailable(context.Context, *Specification, *FindAvailableResp) error
}

func RegisterVesselServiceHandler(s server.Server, hdlr VesselServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&VesselService{hdlr}, opts...))
}

type VesselService struct {
	VesselServiceHandler
}

func (h *VesselService) Create(ctx context.Context, in *Vessel, out *CreateResp) error {
	return h.VesselServiceHandler.Create(ctx, in, out)
}

func (h *VesselService) FindAvailable(ctx context.Context, in *Specification, out *FindAvailableResp) error {
	return h.VesselServiceHandler.FindAvailable(ctx, in, out)
}
