// Code generated by protoc-gen-go. DO NOT EDIT.
// source: consignment/consignment.proto

package shippy_service_consignment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Consignment struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Weight               int32    `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	VesselId             string   `protobuf:"bytes,4,opt,name=vessel_id,json=vesselId,proto3" json:"vessel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Consignment) Reset()         { *m = Consignment{} }
func (m *Consignment) String() string { return proto.CompactTextString(m) }
func (*Consignment) ProtoMessage()    {}
func (*Consignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c6f11f9923110da, []int{0}
}

func (m *Consignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consignment.Unmarshal(m, b)
}
func (m *Consignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consignment.Marshal(b, m, deterministic)
}
func (m *Consignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consignment.Merge(m, src)
}
func (m *Consignment) XXX_Size() int {
	return xxx_messageInfo_Consignment.Size(m)
}
func (m *Consignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Consignment.DiscardUnknown(m)
}

var xxx_messageInfo_Consignment proto.InternalMessageInfo

func (m *Consignment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Consignment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Consignment) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Consignment) GetVesselId() string {
	if m != nil {
		return m.VesselId
	}
	return ""
}

type CreateConsignmentResponse struct {
	Created              bool         `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Consignment          *Consignment `protobuf:"bytes,2,opt,name=consignment,proto3" json:"consignment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateConsignmentResponse) Reset()         { *m = CreateConsignmentResponse{} }
func (m *CreateConsignmentResponse) String() string { return proto.CompactTextString(m) }
func (*CreateConsignmentResponse) ProtoMessage()    {}
func (*CreateConsignmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c6f11f9923110da, []int{1}
}

func (m *CreateConsignmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConsignmentResponse.Unmarshal(m, b)
}
func (m *CreateConsignmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConsignmentResponse.Marshal(b, m, deterministic)
}
func (m *CreateConsignmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConsignmentResponse.Merge(m, src)
}
func (m *CreateConsignmentResponse) XXX_Size() int {
	return xxx_messageInfo_CreateConsignmentResponse.Size(m)
}
func (m *CreateConsignmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConsignmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConsignmentResponse proto.InternalMessageInfo

func (m *CreateConsignmentResponse) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *CreateConsignmentResponse) GetConsignment() *Consignment {
	if m != nil {
		return m.Consignment
	}
	return nil
}

type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c6f11f9923110da, []int{2}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

type GetConsignmentsResponse struct {
	Consignments         []*Consignment `protobuf:"bytes,1,rep,name=consignments,proto3" json:"consignments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetConsignmentsResponse) Reset()         { *m = GetConsignmentsResponse{} }
func (m *GetConsignmentsResponse) String() string { return proto.CompactTextString(m) }
func (*GetConsignmentsResponse) ProtoMessage()    {}
func (*GetConsignmentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c6f11f9923110da, []int{3}
}

func (m *GetConsignmentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConsignmentsResponse.Unmarshal(m, b)
}
func (m *GetConsignmentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConsignmentsResponse.Marshal(b, m, deterministic)
}
func (m *GetConsignmentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConsignmentsResponse.Merge(m, src)
}
func (m *GetConsignmentsResponse) XXX_Size() int {
	return xxx_messageInfo_GetConsignmentsResponse.Size(m)
}
func (m *GetConsignmentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConsignmentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConsignmentsResponse proto.InternalMessageInfo

func (m *GetConsignmentsResponse) GetConsignments() []*Consignment {
	if m != nil {
		return m.Consignments
	}
	return nil
}

func init() {
	proto.RegisterType((*Consignment)(nil), "shippy.service.consignment.Consignment")
	proto.RegisterType((*CreateConsignmentResponse)(nil), "shippy.service.consignment.CreateConsignmentResponse")
	proto.RegisterType((*GetRequest)(nil), "shippy.service.consignment.GetRequest")
	proto.RegisterType((*GetConsignmentsResponse)(nil), "shippy.service.consignment.GetConsignmentsResponse")
}

func init() { proto.RegisterFile("consignment/consignment.proto", fileDescriptor_2c6f11f9923110da) }

var fileDescriptor_2c6f11f9923110da = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0x65, 0x41, 0x11, 0xa6, 0x44, 0xe2, 0x1c, 0x74, 0xad, 0x31, 0x69, 0xf6, 0xa0, 0x9c, 0x6a,
	0x02, 0xf1, 0x17, 0x70, 0x20, 0xc4, 0x5b, 0xf9, 0x01, 0x46, 0xdb, 0xb1, 0x6c, 0xa2, 0xdb, 0xb5,
	0xb3, 0x60, 0xbc, 0xf9, 0xbb, 0x3d, 0x19, 0x5b, 0x95, 0xf5, 0x03, 0xd4, 0xdb, 0xce, 0xcc, 0x7b,
	0x6f, 0xde, 0xbc, 0x2c, 0x1c, 0xa7, 0x85, 0x61, 0x9d, 0x9b, 0x3b, 0x32, 0xee, 0xcc, 0x7b, 0xc7,
	0xb6, 0x2c, 0x5c, 0x81, 0x21, 0xcf, 0xb5, 0xb5, 0x8f, 0x31, 0x53, 0xb9, 0xd4, 0x29, 0xc5, 0x1e,
	0x42, 0x39, 0x08, 0xc6, 0xab, 0x12, 0x77, 0xa1, 0xa9, 0x33, 0x29, 0x22, 0x31, 0xe8, 0x26, 0x4d,
	0x9d, 0x61, 0x04, 0x41, 0x46, 0x9c, 0x96, 0xda, 0x3a, 0x5d, 0x18, 0xd9, 0xac, 0x06, 0x7e, 0x0b,
	0xf7, 0xa1, 0xfd, 0x40, 0x3a, 0x9f, 0x3b, 0xd9, 0x8a, 0xc4, 0x60, 0x3b, 0x79, 0xab, 0xf0, 0x08,
	0xba, 0x4b, 0x62, 0xa6, 0xdb, 0x4b, 0x9d, 0xc9, 0xad, 0x8a, 0xd7, 0xa9, 0x1b, 0xd3, 0x4c, 0x3d,
	0x09, 0x38, 0x1c, 0x97, 0x74, 0xe5, 0xc8, 0x5b, 0x9e, 0x10, 0xdb, 0xc2, 0x30, 0xa1, 0x84, 0x9d,
	0xb4, 0x1a, 0xd6, 0x4e, 0x3a, 0xc9, 0x7b, 0x89, 0x53, 0x08, 0x3c, 0xf3, 0x95, 0x9d, 0x60, 0x78,
	0x1a, 0xaf, 0xbf, 0x2f, 0xf6, 0xf5, 0x7d, 0xae, 0xea, 0x01, 0x4c, 0xc8, 0x25, 0x74, 0xbf, 0x20,
	0x76, 0xea, 0x06, 0x0e, 0x26, 0xe4, 0x3c, 0x30, 0x7f, 0xb8, 0xb9, 0x80, 0x9e, 0xc7, 0x63, 0x29,
	0xa2, 0xd6, 0x7f, 0x96, 0x7e, 0x22, 0x0f, 0x9f, 0x05, 0xf4, 0x67, 0xaf, 0x44, 0x6d, 0xf2, 0x59,
	0xcd, 0xc4, 0x05, 0xec, 0x7d, 0xcb, 0x02, 0xff, 0xaa, 0x1f, 0x9e, 0x6f, 0x04, 0xae, 0xcb, 0x58,
	0x35, 0xd0, 0x42, 0xff, 0xcb, 0xc9, 0x78, 0xb2, 0x49, 0x6b, 0x95, 0x56, 0x38, 0xfa, 0x05, 0xf7,
	0x53, 0x8e, 0xaa, 0x71, 0xdd, 0xae, 0xbe, 0xe3, 0xe8, 0x25, 0x00, 0x00, 0xff, 0xff, 0x21, 0x99,
	0x7f, 0xab, 0xaf, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ShippingService service

type ShippingServiceClient interface {
	CreateConsignment(ctx context.Context, in *Consignment, opts ...client.CallOption) (*CreateConsignmentResponse, error)
	GetConsignments(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetConsignmentsResponse, error)
}

type shippingServiceClient struct {
	c           client.Client
	serviceName string
}

func NewShippingServiceClient(serviceName string, c client.Client) ShippingServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "shippy.service.consignment"
	}
	return &shippingServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *shippingServiceClient) CreateConsignment(ctx context.Context, in *Consignment, opts ...client.CallOption) (*CreateConsignmentResponse, error) {
	req := c.c.NewRequest(c.serviceName, "ShippingService.CreateConsignment", in)
	out := new(CreateConsignmentResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingServiceClient) GetConsignments(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetConsignmentsResponse, error) {
	req := c.c.NewRequest(c.serviceName, "ShippingService.GetConsignments", in)
	out := new(GetConsignmentsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ShippingService service

type ShippingServiceHandler interface {
	CreateConsignment(context.Context, *Consignment, *CreateConsignmentResponse) error
	GetConsignments(context.Context, *GetRequest, *GetConsignmentsResponse) error
}

func RegisterShippingServiceHandler(s server.Server, hdlr ShippingServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&ShippingService{hdlr}, opts...))
}

type ShippingService struct {
	ShippingServiceHandler
}

func (h *ShippingService) CreateConsignment(ctx context.Context, in *Consignment, out *CreateConsignmentResponse) error {
	return h.ShippingServiceHandler.CreateConsignment(ctx, in, out)
}

func (h *ShippingService) GetConsignments(ctx context.Context, in *GetRequest, out *GetConsignmentsResponse) error {
	return h.ShippingServiceHandler.GetConsignments(ctx, in, out)
}
